In [53]:
import numpy as np
import math

In [7]:
y = np.array([
    [3, 0, 1, 2, 7, 4], 
    [1, 5, 8, 9, 3, 1], 
    [2, 7, 2, 5, 1, 3], 
    [0, 1, 3, 1, 7, 8],
    [4, 2, 1, 6, 2, 8],
    [2, 4, 5, 2, 3, 9]
])

x = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

In [5]:
print(y)
print(y.shape)

[[3 0 1 2 7 4]
 [1 5 8 9 3 1]
 [2 7 2 5 1 3]
 [0 1 3 1 7 8]
 [4 2 1 6 2 8]
 [2 4 5 2 3 9]]
(6, 6)


In [8]:
print(x)
print(x.shape)

[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]
(3, 3)


In [17]:
def conv(y, x):
    """
    Arguments
    Results
    """
    
    def conv_kernel(y, x, pos_x, pos_y):
        """
        Arguments
        Results
        """
        res = 0
        for idx_x in range(x.shape[0]):
            for idx_y in range(x.shape[1]):
                res += (y[pos_x + idx_x][pos_y + idx_y] * x[idx_x][idx_y])
            
        return res
    
    res = []
    for pos_x in range(4):
        for pos_y in range(4):
            res.append(conv_kernel(y, x, pos_x, pos_y))
    return np.array(res).reshape(4, 4)

In [18]:
conv(y, x)

array([[ -5,  -4,   0,   8],
       [-10,  -2,   2,   3],
       [  0,  -2,  -4,  -7],
       [ -3,  -2,  -3, -16]])

# Vertical Detection

In [23]:
y = np.array([
    [10, 10, 10, 0, 0, 0], 
    [10, 10, 10, 0, 0, 0], 
    [10, 10, 10, 0, 0, 0], 
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0]
])

x = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

conv(y, x)

array([[ 0, 30, 30,  0],
       [ 0, 30, 30,  0],
       [ 0, 30, 30,  0],
       [ 0, 30, 30,  0]])

In [24]:
y = np.array([
    [0, 0, 0, 10, 10, 10], 
    [0, 0, 0, 10, 10, 10], 
    [0, 0, 0, 10, 10, 10], 
    [0, 0, 0, 10, 10, 10],
    [0, 0, 0, 10, 10, 10],
    [0, 0, 0, 10, 10, 10]
])

x = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

conv(y, x)

array([[  0, -30, -30,   0],
       [  0, -30, -30,   0],
       [  0, -30, -30,   0],
       [  0, -30, -30,   0]])

# Vertical and Horizontal Edge Detection

In [26]:
y = np.array([
    [10, 10, 10,  0,  0,  0], 
    [10, 10, 10,  0,  0,  0], 
    [10, 10, 10,  0,  0,  0], 
    [ 0,  0,  0, 10, 10, 10],
    [ 0,  0,  0, 10, 10, 10],
    [ 0,  0,  0, 10, 10, 10]
])

x1 = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

x2 = np.array([
    [ 1,  1,  1],
    [ 0,  0,  0],
    [-1, -1, -1]
])


print(conv(y, x1))
print("=============")
print(conv(y, x2))

[[  0  30  30   0]
 [  0  10  10   0]
 [  0 -10 -10   0]
 [  0 -30 -30   0]]
[[  0   0   0   0]
 [ 30  10 -10 -30]
 [ 30  10 -10 -30]
 [  0   0   0   0]]


[sobel filter](https://en.wikipedia.org/wiki/Sobel_operator)

In [ ]:
# sobel filter
x = np.array([
    [1, 0, -1],
    [2, 0, -2],
    [1, 0, -1]
])

[Scharr filter](https://www.xilinx.com/html_docs/xilinx2017_4/sdsoc_doc/qpx1504034283355.html)

In [ ]:
# scharr filter
x = np.array([
    [3,  0, -3],
    [10, 0, -10],
    [3,  0, -3]
])

# Padding

In [27]:
y

array([[10, 10, 10,  0,  0,  0],
       [10, 10, 10,  0,  0,  0],
       [10, 10, 10,  0,  0,  0],
       [ 0,  0,  0, 10, 10, 10],
       [ 0,  0,  0, 10, 10, 10],
       [ 0,  0,  0, 10, 10, 10]])

In [29]:
tmp = y
tmp = np.column_stack((
    tmp.shape[0] * [0],
    tmp,
    tmp.shape[0] * [0]))
print(tmp)

[[ 0 10 10 10  0  0  0  0]
 [ 0 10 10 10  0  0  0  0]
 [ 0 10 10 10  0  0  0  0]
 [ 0  0  0  0 10 10 10  0]
 [ 0  0  0  0 10 10 10  0]
 [ 0  0  0  0 10 10 10  0]]


In [30]:
tmp = np.row_stack((
    tmp.shape[1] * [0],
    tmp,
    tmp.shape[1] * [0]))
print(tmp)

[[ 0  0  0  0  0  0  0  0]
 [ 0 10 10 10  0  0  0  0]
 [ 0 10 10 10  0  0  0  0]
 [ 0 10 10 10  0  0  0  0]
 [ 0  0  0  0 10 10 10  0]
 [ 0  0  0  0 10 10 10  0]
 [ 0  0  0  0 10 10 10  0]
 [ 0  0  0  0  0  0  0  0]]


In [40]:
def conv(y, x, padding):
    """
    Arguments
    Results
    """
    def conv_padding(y, padding):
        for _ in range(padding):
            y = np.column_stack((
                y.shape[0] * [0], 
                y, 
                y.shape[0] * [0]))
            y = np.row_stack((
                y.shape[1] * [0],
                y,
                y.shape[1] * [0]))
        return y
    
    def conv_kernel(y, x, pos_x, pos_y):
        res = 0
        for idx_x in range(x.shape[0]):
            for idx_y in range(x.shape[1]):
                res += (y[pos_x + idx_x][pos_y + idx_y] * x[idx_x][idx_y])
            
        return res
    
    res = []
    tmp = conv_padding(y, padding)
    n = tmp.shape[0]
    f = x.shape[0]
    
    for pos_x in range(n - f + 1):
        for pos_y in range(n - f + 1):
            res.append(conv_kernel(tmp, x, pos_x, pos_y))
            
    return np.array(res).reshape(n - f + 1, n - f + 1)

In [38]:
conv(y, x, 1)

array([[-20,   0,  20,  20,   0,   0],
       [-30,   0,  30,  30,   0,   0],
       [-20,   0,  10,  10,   0,  10],
       [-10,   0, -10, -10,   0,  20],
       [  0,   0, -30, -30,   0,  30],
       [  0,   0, -20, -20,   0,  20]])

# Strided Convolution

In [58]:
def conv(y, x, padding, strided):
    """
    Arguments
    Results
    """
    def conv_padding(y, padding):
        for _ in range(padding):
            y = np.column_stack((
                y.shape[0] * [0], 
                y, 
                y.shape[0] * [0]))
            y = np.row_stack((
                y.shape[1] * [0],
                y,
                y.shape[1] * [0]))
        return y
    
    def conv_kernel(y, x, pos_x, pos_y):
        res = 0
        for idx_x in range(x.shape[0]):
            for idx_y in range(x.shape[1]):
                res += (y[pos_x + idx_x][pos_y + idx_y] * x[idx_x][idx_y])
            
        return res
    
    res = []
    tmp = conv_padding(y, padding)
    n = tmp.shape[0]
    f = x.shape[0]
    shape = math.floor((n - f) / strided + 1)
    for pos_x in range(0, n - f + 1, strided):
        for pos_y in range(0, n - f + 1, strided):
            res.append(conv_kernel(tmp, x, pos_x, pos_y))
            
    return np.array(res).reshape(shape, shape)

In [59]:
y = np.array([
    [2, 3, 7, 4, 6, 2, 9],
    [6, 6, 9, 8, 7, 4, 3],
    [3, 4, 8, 3, 8, 9, 7],
    [7, 8, 3, 6, 6, 3, 4],
    [4, 2, 1, 8, 3, 4, 6],
    [3, 2, 4, 1, 9, 8, 3],
    [0, 1, 3, 9, 2, 1, 4]
])

x = np.array([
    [ 3,  4,  4],
    [ 1,  0,  2],
    [-1,  0,  3]
])


print(conv(y, x, 0, 1))
print(conv(y, x, 0, 2))

[[ 91  80 100  84  88]
 [ 99 106 126  92  77]
 [ 69  98  91  93 117]
 [ 80  79  87  93  61]
 [ 44  72  72  63  74]]
[[ 91 100  88]
 [ 69  91 117]
 [ 44  72  74]]


# Convolutions Over Volume

In [68]:
y1 = np.array([
    [10, 10, 10, 0, 0, 0], 
    [10, 10, 10, 0, 0, 0], 
    [10, 10, 10, 0, 0, 0], 
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0]
])

x1 = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

y2 = np.array([
    [0, 0, 0, 10, 10, 10], 
    [0, 0, 0, 10, 10, 10], 
    [0, 0, 0, 10, 10, 10], 
    [0, 0, 0, 10, 10, 10],
    [0, 0, 0, 10, 10, 10],
    [0, 0, 0, 10, 10, 10]
])

x2 = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

y = np.array([y1, y2])
x = np.array([x1, x2])#
res = np.array([0] * 16).reshape(4, 4)
for (tmp_y, tmp_x) in zip(y, x):
    #print(tmp_y)
    #print(tmp_x)
    res += conv(tmp_y, tmp_x, 0, 1)
print(res)



[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
y = np.array([
    [10, 10, 10,  0,  0,  0], 
    [10, 10, 10,  0,  0,  0], 
    [10, 10, 10,  0,  0,  0], 
    [ 0,  0,  0, 10, 10, 10],
    [ 0,  0,  0, 10, 10, 10],
    [ 0,  0,  0, 10, 10, 10]
])

x1 = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

x2 = np.array([
    [ 1,  1,  1],
    [ 0,  0,  0],
    [-1, -1, -1]
])


print(conv(y, x1))
print("=============")
print(conv(y, x2))