In [2]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

# Cost function

Suppose we have a binary classification problem, where **y = 1 or 0**. We can calculate the cost function of our result **$\hat{y}$**.

$$\mathcal{L}(y, \hat{y}) = - \big[ y * log(\hat{y}) + (1 - y) * log(1 - \hat{y}) \big]$$

$$\begin{cases} 
    y = 1 & \rightarrow & \mathcal{L}(y, \hat{y}) = - log(\hat{y}) \\
    y = 0 & \rightarrow & \mathcal{L}(y, \hat{y}) = - log(1 - \hat{y})
\end{cases}$$

In [19]:
def sigmoid(z):
    """
    Compute the sigmoid of z using logistic function 1/(1+e^(-z))
    
    Arguments:
    z --- A scalar or numpy array of any size
    
    Return:
    s --- sigmoid(z)
    """
    # 1/(1+e^(-z))
    s = 1 / (1 + np.exp(-z))
    
    return s

In [30]:
x = np.linspace(start = -5, stop = 5, num = 10, dtype=np.float)
a = sigmoid(x)
y = np.random.binomial(n = 1, p = a, size = 10)

In [61]:
cost = - ( y * np.log(a) + (1 - y) * np.log(1 - a) )
print(np.array([" Y        ", "Yhat     ", "Cost"]))
print(np.array([y, a, cost]).transpose())

[' Y        ' 'Yhat     ' 'Cost']
[[ 0.          0.00669285  0.00671535]
 [ 0.          0.02005754  0.02026142]
 [ 0.          0.0585369   0.06032013]
 [ 0.          0.1588691   0.17300799]
 [ 1.          0.36457644  1.00901904]
 [ 0.          0.63542356  1.00901904]
 [ 1.          0.8411309   0.17300799]
 [ 1.          0.9414631   0.06032013]
 [ 1.          0.97994246  0.02026142]
 [ 1.          0.99330715  0.00671535]]


# Cost function of m samples

$$(x^{(1)}, y^{(1)}), (x^{(2)}, y^{(2)}), ..., (x^{(m)}, y^{(m)})$$

$$\hat{y}^{(i)} = \sigma(w^Tx^{(i)}+b)$$

$$J(w, b) = \frac{1}{m}\sum\mathcal{L}(y^{(i)}, \hat{y}^{(i)}) = - \big[ y * log(\hat{y}) + (1 - y) * log(1 - \hat{y}) \big]$$

In [63]:
m = len(y)
cost = 1/m * -np.sum(y * np.log(a) + (1 - y) * np.log(1 - a))

In [64]:
print(cost)

0.253864784041
