In [1]:
import numpy as np

In [9]:
a = np.random.randn(3)
print(a)

[-1.21121226 -0.24978704 -0.87597854]


In [10]:
print(a.shape)

(3,)


In [12]:
print(a.T)

[-1.21121226 -0.24978704 -0.87597854]


In [13]:
print(np.dot(a, a.T))

2.2967671046


It turns out that "a" is not a row or column vector. It is a **rank one array**.

Therefore we should avoid using this kind of array. Instead, we should:

In [14]:
a = np.random.randn(3,1)
print(a)

[[-0.83577564]
 [-0.2217667 ]
 [ 1.44343256]]


In [15]:
print(a.T) # notice that there are two square bracket

[[-0.83577564 -0.2217667   1.44343256]]


In [16]:
print(np.dot(a, a.T))

[[ 0.69852091  0.18534721 -1.20638577]
 [ 0.18534721  0.04918047 -0.32010528]
 [-1.20638577 -0.32010528  2.08349757]]
